### ISSUE TITLE
Alpha has been published to npm using latest tag

### ISSUE THREAD

**Issue by mcfarljw** [nemisj/git-removed-branches#16]
It prompted me to update to the latest `2.3.1-alpha.0` from the `2.3.0` stable (https://www.npmjs.com/package/git-removed-branches?activeTab=versions). If this wasn't intended then you can fix the tags by using `npm dist-tag add git-removed-branches@2.3.1-alpha.0 alpha` so that it's an opt in upgrade until officially released.

**Comment by nemisj** [comment]
That's a very good point. thanks @mcfarljw i've updated tags and put 2.3.0 to the latest
