### ISSUE TITLE
Python version as a module at pypi.org

### ISSUE THREAD

**Issue by glasswalk3r** [nemisj/git-removed-branches#5]
Hi there,

First, this is actually not a issue!
Second, thanks for writing sharing this code, really useful!
Since you have made a Python version, what do you think about releasing it as a Python module so it could be easily published (and installed from) [http://pypi.org](http://pypi.org)?
I'm willing to help with all the process, just let me know if you think it's a good idea.
Regards,
Alceu

**Comment by nemisj** [comment]
@glasswalk3r yeah, sure, good idea :) if you will help, that would be great, cause I have no idea how to do that. Let's communicate through email - info@nemisj.com, I will close this issue :)
